{% set name = "fgclustering" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "e3dbba85860943cfe704e2617caf419f00e47e01039780466659ce76313fafb7"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.12
    - pandas
    - numpy
    - matplotlib-base
    - seaborn >=0.12
    - scikit-learn
    - kmedoids
    - scipy
    - tqdm
    - statsmodels >=0.13.5
    - numexpr >=2.8.4
    - numba

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fgclustering

about:
  home: "https://github.com/HelmholtzAI-Consultants-Munich/fg-clustering"
  summary: "Explainability for Random Forest Models."
  license: "MIT"
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IsraMekki0
